### ISSUE TITLE
Version should be an integer greater than 0 for environments

### ISSUE THREAD

**Issue by andreasbotsikas** [microsoft/vscode-tools-for-ai#1516]
## Expected Behavior
In component definition, allow Environment versions to be strings like dates.

## Actual Behavior
VS code plugin puts a curly bracket under the environment when targeting a version that is in the yyyy-mm-dd format.
![image](https://user-images.githubusercontent.com/1227433/160792885-88b8a3f3-a9ee-46e1-81ae-bb3f4a0f3ab1.png)

## Steps to Reproduce the Problem

  1. Create an environment using the following definition:
      ```yaml
      $schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
      name: forecast-r-environment
      version: '2022-02-03'
      build:
        local_path: environment
      ```
     Note that version in this schema is a string, something supported by the definition.
  1. Publish environment in AzureML using [CLI v2](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2)
  1. Create a component yaml file and try to use the environment referencing it as `azureml:environment-name:version`. Like [this sample component](https://github.com/rndazurescript/FunWithAzureML/blob/master/cli-v2-r-forecasting/30.component_a-pre-process-sql-data.yml)

See that VS code shows the following error: `Version should be an integer greater than 0 for environments`

## Specifications

  - Version: ms-toolsai.vscode-ai v0.6.28
  - Platform: 
     ``` Version: 1.65.2 (system setup)
     Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
     Date: 2022-03-10T14:33:55.248Z
     Electron: 13.5.2
     Chromium: 91.0.4472.164
     Node.js: 14.16.0
     V8: 9.1.269.39-electron.0
     OS: Windows_NT x64 10.0.19044
     ```
