### ISSUE TITLE
Problem after upgrade to the latest version

### ISSUE THREAD

**Issue by mlomat** [microsoft/vscode-tools-for-ai#1520]
## Expected Behavior
Connection to Compute Instance

## Actual Behavior
Error: 
![image](https://user-images.githubusercontent.com/7577121/161244373-ec617d1c-5bf6-410c-b212-1390491b2c34.png)

## Steps to Reproduce the Problem

  1. Whole team cannot connect to their compute instances today
  1. I created a new compute instance, installed new VS Code with the latest plugin, and after I click on a link in ML Studio portal, it's failing to connect. 
  1. I cannot also connect from VSCode directly. When I try to connect from console with Azure ML: Connect to Compute Instance, it's only showing my subscription and later ML workspace, but on step when I should choose Compute Instance it's empty list.

## Specifications

  - VS Code Version: 
  Version: 1.66.0 (system setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
- Azure Machine Learning: v0.8.0
- Azure Machine Learning Remote: v0.10.0

**Comment by MalteHB** [comment]
Same issue here.

**Comment by jbschiratti** [comment]
Same issue here. In VS Code, I no longer have the possibility to connect to a compute instance using the Azure Machine Learning extension. More specifically, when I click right on the name of the compute instance, I have the following options: "Start", "Restart", "Delete", "View Properties". The previous version also had: "Connect to compute instance". 

A few weeks ago, the version 0.7 of the "Azure Machine Learning" extension for VS Code was buggy. A new version (0.8) of the same extension was released 15 hours after 0.7 to correct the bug. Is this another buggy release? Do you guys use CI/CD tools before releasing new versions??? Seriously?!

--- 
macOS Monterey (version 12.2.1)
VS Code version 1.66.0
Azure Machine Learning extension version 0.8.0

**Comment by jbschiratti** [comment]
@sevillal @shsuman Any comment on this?

**Comment by mlomat** [comment]
> Same issue here. In VS Code, I no longer have the possibility to connect to a compute instance using the Azure Machine Learning extension. More specifically, when I click right on the name of the compute instance, I have the following options: "Start", "Restart", "Delete", "View Properties". With the previous version of the extension, I also had: "Connect to compute instance".
> 
> A few weeks ago, the version 0.7 of the "Azure Machine Learning" extension for VS Code was buggy. A new version (0.8) of the same extension was released 15 hours after 0.7 to correct the bug. Is this another buggy release? Do you guys use CI/CD tools before releasing new versions??? Seriously?! 👎
> 
> macOS Monterey (version 12.2.1) VS Code version 1.66.0 Azure Machine Learning extension version 0.8.0

I can confirm that. My team also cannot see option connect to. So it looks like total mess :(

**Comment by jbschiratti** [comment]
Yes, unfortunately. I don't know who's in charge of maintaining this repository... top contributors have 10-15 commits max so I guess this is more a front?! Anyway, someone somewhere should think seriously about code reviews! I expected more from a company such as Microsoft. Disappointed!

**Comment by shsuman** [comment]
@mlomat , @jbschiratti , @MalteHB First of all accept my deepest apologies for the problems you are facing. With this new release, we have made some heavy code changes and also migrated to a new backend API which seems to be the root cause of this issue. However, I would like to ensure you that we are investigating the issue on a priority basis and will ship a fix ASAP.

Can you all please answer a few of my questions so we can get this fixed ASAP for you :)
1. Are you using assigned Compute instances (i.e. someone else created it for you e.g. admin in your org)
2. Can you please send me the Compute instance's properties. You can view Compute instance's properties by right clicking on the Compute in the tree and then click on **View Properties**. Please be aware that properties might contain some PII, so please redact those before uploading.

In the meantime, I would suggested you to downgrade both the extensions (Azure Machine Learning and Azure Machine Learning - Remote) to the previous version using the instructions [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions)

**Comment by shsuman** [comment]
@mlomat For your problems with the "Unsupported legacy remote authority", Can you please click the **Close Remote Connection** button on the error message and try again. Since you are not seeing your Compute instances in VSCode, my guess is you will some permissions error.

**Comment by mlomat** [comment]
> @mlomat For your problems with the "Unsupported legacy remote authority", Can you please click the **Close Remote Connection** button on the error message and try again. Since you are not seeing your Compute instances in VSCode, my guess is you will some permissions error.

Downgrading the version was the first thing which I did, but I still have this same issue. Nothing has changed in permission. Everything was working fine yesterday. 
Answer for your questions. 
1. Yes, I am creating them for Data Scientist team. But for myself, I have this same error. 
2. Properties: 

```
id: >-
  /subscriptions/xxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test-rg/providers/Microsoft.MachineLearningServices/workspaces/test-ml/computes/mct-matesttoremove
name: mct-matesttoremove
type: Microsoft.MachineLearningServices/workspaces/computes
location: westeurope
tags: {}
properties:
  createdOn: '2022-04-01T09:43:54.4391063+00:00'
  modifiedOn: '2022-04-01T09:48:00.3338527+00:00'
  disableLocalAuth: true
  description: null
  resourceId: null
  computeType: ComputeInstance
  computeLocation: westeurope
  provisioningState: Succeeded
  provisioningErrors: null
  isAttachedCompute: false
  properties:
    vmSize: STANDARD_DS3_V2
    subnet:
      id: >-
        /subscriptions/xxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test-rg/providers/Microsoft.Network/virtualNetworks/test-vnet/subnets/Main
    sshSettings:
      sshPublicAccess: Disabled
      adminUserName: azureuser
      sshPort: 4000
    errors: []
    connectivityEndpoints:
      publicIpAddress: 1.2.3.4
      privateIpAddress: 5.6.7.8
    applications:
      - displayName: Jupyter
        endpointUri: 'https://mct-matesttoremove.westeurope.instances.azureml.ms/tree/'
      - displayName: Jupyter Lab
        endpointUri: 'https://mct-matesttoremove.westeurope.instances.azureml.ms/lab'
      - displayName: RStudio
        endpointUri: 'https://mct-matesttoremove-8787.westeurope.instances.azureml.ms'
    state: Running
    lastOperation:
      operationName: Create
      operationTime: '2022-04-01T09:43:58.621+00:00'
      operationStatus: Succeeded
      operationTrigger: User
    createdBy:
      userOrgId: xxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      userId: xxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
    applicationSharingPolicy: Shared
    computeInstanceAuthorizationType: null
    personalComputeInstanceSettings: null
    setupScripts: null
    schedules:
      computeStartStop:
        - triggerType: Cron
          recurrence: null
          cron:
            expression: '00 20 * * 0,1,2,3,4,5,6'
            startTime: '2022-03-30T10:32:31'
            timeZone: UTC
          action: Stop
          id: xxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
          status: Enabled
          provisioningStatus: Completed
    dataMounts: null
    dataDisks: null
    containers: null
    updateStatus: null
    versions:
      runtime: 3.0.01901.0001

```
