### ISSUE TITLE
f

### ISSUE THREAD

**Issue by janluis007** [microsoft/vscode-tools-for-ai#1610]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.explorerContext.executeYaml
Error type: r
Error Message: The YAML file does not contain a "$schema" tag or "yaml-language-server" comment. Please update the file before creating the resource.

Version: 0.12.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

<details>
<summary>Call Stack</summary>

```
H.<anonymous> extension.js:2:2759200
s extension.js:2:2758177
```

</details>

**Comment by tbombach** [comment]
Hi @janluis007. Would you mind sharing how you created your Yaml file? Typically these files should have a $schema property at the top of the file based on the intended operation and it determines how we validate the file. If you run the command "Azure ML: Create Job", you can create a command job file that looks like this:
```
$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
#enter path to your script files
code: <path-to-your-scripts>
#use scripts in Python, R, Java, Julia, C#. Here we have shown python
command: python <placeholder-for-your-script-name> --data ${{inputs.trainingData1}}
# invoke completions (Ctrl+Space, Cmd+Space) to see the list of environments available
environment:
  image: docker.io/python
# invoke completions (Ctrl+Space, Cmd+Space) to see the list of computes available
compute: azureml:cpu-cluster
# This defines the input data to mount. The names of the items in inputs can be referenced in the command
inputs:
  trainingData1:
    type: uri_file
    mode: ro_mount
    path: <path-to-your-local-training-data>
  trainingData2:
    type: uri_folder
    mode: ro_mount
    path: <url-to-blob-container-with-data>
```

Does you YAML file have a $schema property at the top of your file?
